"""
Tenant Recommendation Model - AI-powered tenant mix optimization
"""
from sqlalchemy import Column, Integer, String, Date, DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from app.db.database import Base


class TenantRecommendation(Base):
    """
    Tenant Recommendations - AI-powered suggestions for vacant spaces

    Stores recommendations generated by tenant recommendation AI
    """
    __tablename__ = "tenant_recommendations"

    id = Column(Integer, primary_key=True, index=True)
    property_id = Column(Integer, ForeignKey("properties.id", ondelete="CASCADE"), nullable=False, index=True)
    unit_identifier = Column(String(100), nullable=True, comment="Unit/space identifier")
    space_sqft = Column(Integer, nullable=True, comment="Space size in square feet")
    recommendation_date = Column(Date, nullable=False, index=True)

    # JSON fields
    recommendations = Column(JSONB, nullable=False, comment="Array of recommendation objects with scores")
    demographics_used = Column(JSONB, nullable=True, comment="Demographics data used for recommendations")
    tenant_mix_used = Column(JSONB, nullable=True, comment="Current tenant mix at time of recommendation")

    # Timestamps
    created_at = Column(DateTime, server_default=func.now())

    # Relationships
    property_obj = relationship("Property", back_populates="tenant_recommendations")

    def __repr__(self):
        return f"<TenantRecommendation(id={self.id}, property_id={self.property_id}, unit={self.unit_identifier})>"

    @property
    def top_recommendation(self):
        """Get the top-ranked recommendation"""
        if self.recommendations and len(self.recommendations) > 0:
            # Assuming recommendations are pre-sorted by score
            return self.recommendations[0]
        return None

    def get_recommendations_by_category(self, category: str):
        """Get all recommendations for a specific category"""
        if not self.recommendations:
            return []
        return [r for r in self.recommendations if r.get('tenant_type') == category]

    def to_dict(self):
        """Convert to dictionary"""
        return {
            'id': self.id,
            'property_id': self.property_id,
            'unit_identifier': self.unit_identifier,
            'space_sqft': self.space_sqft,
            'recommendation_date': self.recommendation_date.isoformat() if self.recommendation_date else None,
            'recommendations': self.recommendations,
            'demographics_used': self.demographics_used,
            'tenant_mix_used': self.tenant_mix_used,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
