-- Manual Schema Fixes Applied on 2025-11-08
-- These were applied directly to fix extraction failures
-- Run this script if recreating the database from scratch

-- Fix extraction_logs table
ALTER TABLE extraction_logs 
ADD COLUMN IF NOT EXISTS file_hash VARCHAR(32),
ADD COLUMN IF NOT EXISTS strategy_used VARCHAR(50),
ADD COLUMN IF NOT EXISTS engines_used JSONB,
ADD COLUMN IF NOT EXISTS primary_engine VARCHAR(50),
ADD COLUMN IF NOT EXISTS quality_level VARCHAR(20),
ADD COLUMN IF NOT EXISTS passed_checks INTEGER,
ADD COLUMN IF NOT EXISTS total_checks INTEGER,
ADD COLUMN IF NOT EXISTS processing_time_seconds NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS validation_issues JSONB,
ADD COLUMN IF NOT EXISTS validation_warnings JSONB,
ADD COLUMN IF NOT EXISTS recommendations JSONB,
ADD COLUMN IF NOT EXISTS extracted_text TEXT,
ADD COLUMN IF NOT EXISTS text_preview TEXT,
ADD COLUMN IF NOT EXISTS total_words INTEGER,
ADD COLUMN IF NOT EXISTS total_chars INTEGER,
ADD COLUMN IF NOT EXISTS tables_found INTEGER,
ADD COLUMN IF NOT EXISTS images_found INTEGER,
ADD COLUMN IF NOT EXISTS needs_review BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reviewed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS review_notes TEXT,
ADD COLUMN IF NOT EXISTS custom_metadata JSONB,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Fix income_statement_data table
ALTER TABLE income_statement_data
ADD COLUMN IF NOT EXISTS header_id INTEGER REFERENCES income_statement_headers(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS account_id INTEGER REFERENCES chart_of_accounts(id),
ADD COLUMN IF NOT EXISTS period_percentage NUMERIC(7,4),
ADD COLUMN IF NOT EXISTS ytd_percentage NUMERIC(7,4),
ADD COLUMN IF NOT EXISTS report_generation_date DATE,
ADD COLUMN IF NOT EXISTS is_below_the_line BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS extraction_method VARCHAR(50),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS reviewed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS review_notes TEXT;

-- Fix cash_flow_data table
ALTER TABLE cash_flow_data
ADD COLUMN IF NOT EXISTS header_id INTEGER REFERENCES cash_flow_headers(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS account_id INTEGER REFERENCES chart_of_accounts(id),
ADD COLUMN IF NOT EXISTS period_percentage NUMERIC(7,4),
ADD COLUMN IF NOT EXISTS ytd_percentage NUMERIC(7,4),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS reviewed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS review_notes TEXT;

-- Fix balance_sheet_data table
ALTER TABLE balance_sheet_data
ADD COLUMN IF NOT EXISTS account_id INTEGER REFERENCES chart_of_accounts(id),
ADD COLUMN IF NOT EXISTS report_date DATE,
ADD COLUMN IF NOT EXISTS is_debit BOOLEAN,
ADD COLUMN IF NOT EXISTS is_contra_account BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_calculated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS parent_account_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS expected_sign VARCHAR(10),
ADD COLUMN IF NOT EXISTS extraction_method VARCHAR(50),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS reviewed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS review_notes TEXT;

-- Applied: 2025-11-08
-- Total columns added: 70+ across 4 tables

