"""Initial financial schema with 13 tables

Revision ID: 61e979087abb
Revises: 
Create Date: 2025-11-03 12:59:38.433359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61e979087abb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('parent_account_code', sa.String(length=50), nullable=True),
    sa.Column('document_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), nullable=True),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_of_accounts_account_code'), 'chart_of_accounts', ['account_code'], unique=True)
    op.create_index(op.f('ix_chart_of_accounts_account_type'), 'chart_of_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_chart_of_accounts_category'), 'chart_of_accounts', ['category'], unique=False)
    op.create_index(op.f('ix_chart_of_accounts_id'), 'chart_of_accounts', ['id'], unique=False)
    op.create_table('extraction_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('template_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('extraction_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_index(op.f('ix_extraction_templates_id'), 'extraction_templates', ['id'], unique=False)
    op.create_table('validation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_formula', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_changed_at'), 'audit_trail', ['changed_at'], unique=False)
    op.create_index(op.f('ix_audit_trail_changed_by'), 'audit_trail', ['changed_by'], unique=False)
    op.create_index(op.f('ix_audit_trail_id'), 'audit_trail', ['id'], unique=False)
    op.create_index(op.f('ix_audit_trail_record_id'), 'audit_trail', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_table_name'), 'audit_trail', ['table_name'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_code', sa.String(length=50), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('total_area_sqft', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('ownership_structure', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_property_code'), 'properties', ['property_code'], unique=True)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_table('financial_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'period_year', 'period_month', name='uq_property_period')
    )
    op.create_index(op.f('ix_financial_periods_id'), 'financial_periods', ['id'], unique=False)
    op.create_index(op.f('ix_financial_periods_period_year'), 'financial_periods', ['period_year'], unique=False)
    op.create_index(op.f('ix_financial_periods_property_id'), 'financial_periods', ['property_id'], unique=False)
    op.create_table('document_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('extraction_status', sa.String(length=50), nullable=True),
    sa.Column('extraction_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction_logs.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'period_id', 'document_type', 'version', name='uq_property_period_doctype_version')
    )
    op.create_index(op.f('ix_document_uploads_document_type'), 'document_uploads', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_uploads_extraction_status'), 'document_uploads', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_document_uploads_id'), 'document_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_document_uploads_period_id'), 'document_uploads', ['period_id'], unique=False)
    op.create_index(op.f('ix_document_uploads_property_id'), 'document_uploads', ['property_id'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('total_assets', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_equity', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('current_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('total_revenue', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_expenses', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('net_operating_income', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('net_income', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('operating_margin', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('profit_margin', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('operating_cash_flow', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('investing_cash_flow', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('financing_cash_flow', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('net_cash_flow', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('beginning_cash_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ending_cash_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('occupied_units', sa.Integer(), nullable=True),
    sa.Column('vacant_units', sa.Integer(), nullable=True),
    sa.Column('occupancy_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_leasable_sqft', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('occupied_sqft', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_monthly_rent', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_annual_rent', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('avg_rent_per_sqft', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('noi_per_sqft', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('revenue_per_sqft', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('expense_ratio', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'period_id', name='uq_metrics_property_period')
    )
    op.create_index(op.f('ix_financial_metrics_id'), 'financial_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_financial_metrics_period_id'), 'financial_metrics', ['period_id'], unique=False)
    op.create_index(op.f('ix_financial_metrics_property_id'), 'financial_metrics', ['property_id'], unique=False)
    op.create_table('balance_sheet_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('is_debit', sa.Boolean(), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), nullable=True),
    sa.Column('parent_account_code', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'period_id', 'account_code', name='uq_bs_property_period_account')
    )
    op.create_index(op.f('ix_balance_sheet_data_account_code'), 'balance_sheet_data', ['account_code'], unique=False)
    op.create_index(op.f('ix_balance_sheet_data_id'), 'balance_sheet_data', ['id'], unique=False)
    op.create_index(op.f('ix_balance_sheet_data_needs_review'), 'balance_sheet_data', ['needs_review'], unique=False)
    op.create_index(op.f('ix_balance_sheet_data_period_id'), 'balance_sheet_data', ['period_id'], unique=False)
    op.create_index(op.f('ix_balance_sheet_data_property_id'), 'balance_sheet_data', ['property_id'], unique=False)
    op.create_table('cash_flow_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('period_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('ytd_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('period_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ytd_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cash_flow_category', sa.String(length=50), nullable=True),
    sa.Column('is_inflow', sa.Boolean(), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), nullable=True),
    sa.Column('parent_account_code', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'period_id', 'account_code', name='uq_cf_property_period_account')
    )
    op.create_index(op.f('ix_cash_flow_data_cash_flow_category'), 'cash_flow_data', ['cash_flow_category'], unique=False)
    op.create_index(op.f('ix_cash_flow_data_id'), 'cash_flow_data', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_data_period_id'), 'cash_flow_data', ['period_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_data_property_id'), 'cash_flow_data', ['property_id'], unique=False)
    op.create_table('income_statement_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('period_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('ytd_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('period_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ytd_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), nullable=True),
    sa.Column('parent_account_code', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'period_id', 'account_code', name='uq_is_property_period_account')
    )
    op.create_index(op.f('ix_income_statement_data_account_code'), 'income_statement_data', ['account_code'], unique=False)
    op.create_index(op.f('ix_income_statement_data_id'), 'income_statement_data', ['id'], unique=False)
    op.create_index(op.f('ix_income_statement_data_period_id'), 'income_statement_data', ['period_id'], unique=False)
    op.create_index(op.f('ix_income_statement_data_property_id'), 'income_statement_data', ['property_id'], unique=False)
    op.create_table('rent_roll_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_code', sa.String(length=50), nullable=True),
    sa.Column('lease_type', sa.String(length=50), nullable=True),
    sa.Column('lease_start_date', sa.Date(), nullable=True),
    sa.Column('lease_end_date', sa.Date(), nullable=True),
    sa.Column('lease_term_months', sa.Integer(), nullable=True),
    sa.Column('remaining_lease_years', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('unit_area_sqft', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('monthly_rent', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('monthly_rent_per_sqft', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('annual_rent', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('annual_rent_per_sqft', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('gross_rent', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('security_deposit', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('loc_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('annual_cam_reimbursement', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('annual_tax_reimbursement', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('annual_insurance_reimbursement', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('occupancy_status', sa.String(length=50), nullable=True),
    sa.Column('lease_status', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'period_id', 'unit_number', name='uq_rr_property_period_unit')
    )
    op.create_index(op.f('ix_rent_roll_data_id'), 'rent_roll_data', ['id'], unique=False)
    op.create_index(op.f('ix_rent_roll_data_lease_end_date'), 'rent_roll_data', ['lease_end_date'], unique=False)
    op.create_index(op.f('ix_rent_roll_data_occupancy_status'), 'rent_roll_data', ['occupancy_status'], unique=False)
    op.create_index(op.f('ix_rent_roll_data_period_id'), 'rent_roll_data', ['period_id'], unique=False)
    op.create_index(op.f('ix_rent_roll_data_property_id'), 'rent_roll_data', ['property_id'], unique=False)
    op.create_index(op.f('ix_rent_roll_data_tenant_name'), 'rent_roll_data', ['tenant_name'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('expected_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('actual_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('difference', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('difference_percentage', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    op.create_index(op.f('ix_validation_results_passed'), 'validation_results', ['passed'], unique=False)
    op.create_index(op.f('ix_validation_results_upload_id'), 'validation_results', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_upload_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_passed'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_rent_roll_data_tenant_name'), table_name='rent_roll_data')
    op.drop_index(op.f('ix_rent_roll_data_property_id'), table_name='rent_roll_data')
    op.drop_index(op.f('ix_rent_roll_data_period_id'), table_name='rent_roll_data')
    op.drop_index(op.f('ix_rent_roll_data_occupancy_status'), table_name='rent_roll_data')
    op.drop_index(op.f('ix_rent_roll_data_lease_end_date'), table_name='rent_roll_data')
    op.drop_index(op.f('ix_rent_roll_data_id'), table_name='rent_roll_data')
    op.drop_table('rent_roll_data')
    op.drop_index(op.f('ix_income_statement_data_property_id'), table_name='income_statement_data')
    op.drop_index(op.f('ix_income_statement_data_period_id'), table_name='income_statement_data')
    op.drop_index(op.f('ix_income_statement_data_id'), table_name='income_statement_data')
    op.drop_index(op.f('ix_income_statement_data_account_code'), table_name='income_statement_data')
    op.drop_table('income_statement_data')
    op.drop_index(op.f('ix_cash_flow_data_property_id'), table_name='cash_flow_data')
    op.drop_index(op.f('ix_cash_flow_data_period_id'), table_name='cash_flow_data')
    op.drop_index(op.f('ix_cash_flow_data_id'), table_name='cash_flow_data')
    op.drop_index(op.f('ix_cash_flow_data_cash_flow_category'), table_name='cash_flow_data')
    op.drop_table('cash_flow_data')
    op.drop_index(op.f('ix_balance_sheet_data_property_id'), table_name='balance_sheet_data')
    op.drop_index(op.f('ix_balance_sheet_data_period_id'), table_name='balance_sheet_data')
    op.drop_index(op.f('ix_balance_sheet_data_needs_review'), table_name='balance_sheet_data')
    op.drop_index(op.f('ix_balance_sheet_data_id'), table_name='balance_sheet_data')
    op.drop_index(op.f('ix_balance_sheet_data_account_code'), table_name='balance_sheet_data')
    op.drop_table('balance_sheet_data')
    op.drop_index(op.f('ix_financial_metrics_property_id'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_period_id'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_id'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index(op.f('ix_document_uploads_property_id'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_period_id'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_id'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_extraction_status'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_document_type'), table_name='document_uploads')
    op.drop_table('document_uploads')
    op.drop_index(op.f('ix_financial_periods_property_id'), table_name='financial_periods')
    op.drop_index(op.f('ix_financial_periods_period_year'), table_name='financial_periods')
    op.drop_index(op.f('ix_financial_periods_id'), table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_audit_trail_table_name'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_record_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_changed_by'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_changed_at'), table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_extraction_templates_id'), table_name='extraction_templates')
    op.drop_table('extraction_templates')
    op.drop_index(op.f('ix_chart_of_accounts_id'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_category'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_account_type'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_account_code'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
