"""Create cash_flow_headers, adjustments, and reconciliations tables

Revision ID: e2a0c73f4cd7
Revises: 939c6b495488
Create Date: 2025-11-04 21:28:21.339034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a0c73f4cd7'
down_revision: Union[str, Sequence[str], None] = '939c6b495488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create cash_flow_headers table
    op.create_table(
        'cash_flow_headers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=False),
        sa.Column('period_id', sa.Integer(), nullable=False),
        sa.Column('upload_id', sa.Integer(), nullable=True),
        sa.Column('property_name', sa.String(length=255), nullable=False),
        sa.Column('property_code', sa.String(length=50), nullable=False),
        sa.Column('report_period_start', sa.Date(), nullable=False),
        sa.Column('report_period_end', sa.Date(), nullable=False),
        sa.Column('accounting_basis', sa.String(length=50), nullable=False),
        sa.Column('report_generation_date', sa.Date(), nullable=True),
        sa.Column('total_income', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('base_rentals', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('total_operating_expenses', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('total_additional_operating_expenses', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('total_expenses', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('net_operating_income', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('noi_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('mortgage_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('depreciation', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('amortization', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('total_other_income_expense', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('net_income', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('net_income_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('total_adjustments', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('cash_flow', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('cash_flow_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('beginning_cash_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('ending_cash_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('extraction_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('needs_review', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('property_id', 'period_id', name='uq_cf_header_property_period')
    )
    op.create_index(op.f('ix_cash_flow_headers_period_id'), 'cash_flow_headers', ['period_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_headers_property_id'), 'cash_flow_headers', ['property_id'], unique=False)
    
    # Create cash_flow_adjustments table
    op.create_table(
        'cash_flow_adjustments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('header_id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=False),
        sa.Column('period_id', sa.Integer(), nullable=False),
        sa.Column('upload_id', sa.Integer(), nullable=True),
        sa.Column('adjustment_category', sa.String(length=100), nullable=True),
        sa.Column('adjustment_name', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('is_increase', sa.Boolean(), nullable=True),
        sa.Column('related_property', sa.String(length=255), nullable=True),
        sa.Column('related_entity', sa.String(length=255), nullable=True),
        sa.Column('line_number', sa.Integer(), nullable=True),
        sa.Column('page_number', sa.Integer(), nullable=True),
        sa.Column('extraction_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('needs_review', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['header_id'], ['cash_flow_headers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_adjustments_adjustment_category'), 'cash_flow_adjustments', ['adjustment_category'], unique=False)
    op.create_index(op.f('ix_cash_flow_adjustments_header_id'), 'cash_flow_adjustments', ['header_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_adjustments_period_id'), 'cash_flow_adjustments', ['period_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_adjustments_property_id'), 'cash_flow_adjustments', ['property_id'], unique=False)
    
    # Create cash_account_reconciliations table
    op.create_table(
        'cash_account_reconciliations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('header_id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=False),
        sa.Column('period_id', sa.Integer(), nullable=False),
        sa.Column('upload_id', sa.Integer(), nullable=True),
        sa.Column('account_name', sa.String(length=255), nullable=False),
        sa.Column('account_type', sa.String(length=50), nullable=True),
        sa.Column('beginning_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('ending_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('difference', sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column('is_escrow_account', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('is_negative_balance', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('is_total_row', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('line_number', sa.Integer(), nullable=True),
        sa.Column('page_number', sa.Integer(), nullable=True),
        sa.Column('extraction_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('needs_review', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['header_id'], ['cash_flow_headers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_account_reconciliations_header_id'), 'cash_account_reconciliations', ['header_id'], unique=False)
    op.create_index(op.f('ix_cash_account_reconciliations_period_id'), 'cash_account_reconciliations', ['period_id'], unique=False)
    op.create_index(op.f('ix_cash_account_reconciliations_property_id'), 'cash_account_reconciliations', ['property_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order (respecting foreign key constraints)
    op.drop_index(op.f('ix_cash_account_reconciliations_property_id'), table_name='cash_account_reconciliations')
    op.drop_index(op.f('ix_cash_account_reconciliations_period_id'), table_name='cash_account_reconciliations')
    op.drop_index(op.f('ix_cash_account_reconciliations_header_id'), table_name='cash_account_reconciliations')
    op.drop_table('cash_account_reconciliations')
    
    op.drop_index(op.f('ix_cash_flow_adjustments_property_id'), table_name='cash_flow_adjustments')
    op.drop_index(op.f('ix_cash_flow_adjustments_period_id'), table_name='cash_flow_adjustments')
    op.drop_index(op.f('ix_cash_flow_adjustments_header_id'), table_name='cash_flow_adjustments')
    op.drop_index(op.f('ix_cash_flow_adjustments_adjustment_category'), table_name='cash_flow_adjustments')
    op.drop_table('cash_flow_adjustments')
    
    op.drop_index(op.f('ix_cash_flow_headers_property_id'), table_name='cash_flow_headers')
    op.drop_index(op.f('ix_cash_flow_headers_period_id'), table_name='cash_flow_headers')
    op.drop_table('cash_flow_headers')
    
    # ### end Alembic commands ###
